export const container: string;
export const header: string;
export const column: string;
export const updateStatusForm: string;
export const refundForm: string;
export const billing: string;
export const billingRow: string;
export const billingColumn: string;
export const billingIcon: string;
