<Project>
  <PropertyGroup>
    <UseProjectReferences>true</UseProjectReferences>
    <Version>0.2.291</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'Ekom.Tests'">
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Ekom.Tests'">
    <None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath=""/>
    <None Include="$(MSBuildThisFileDirectory)CHANGELOG.md" Pack="true" PackagePath=""/>
  </ItemGroup>
</Project>
