<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Package properties -->
        <PackageId>Ekom.Klaviyo</PackageId>
        <Title>Ekom Klaviyo Plugin</Title>
        <Description>Ekom - Klaviyo integration plugin for Umbraco</Description>
        <Authors>Vettvangur</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Vettvangur/Ekom</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Vettvangur/Ekom</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <PackageReleaseNotes></PackageReleaseNotes>
        <Copyright>Copyright 2025</Copyright>
        <PackageTags>umbraco;ecommerce;ekom;b2c;b2b;klaviyo,plugin,extension</PackageTags>

        <!-- Icon & README -->
        <PackageIcon>images/VV_Logo.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <!-- Symbols & SourceLink -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <!-- Build / docs -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    </PropertyGroup>

    <ItemGroup>
        <None Include="./README.md" Link="README.md">
            <PackagePath>\</PackagePath>
            <Pack>true</Pack>
        </None>
        <None Include="./VV_Logo.png" Link="VV_Logo.png">
            <PackagePath>images\</PackagePath>
            <Pack>true</Pack>
        </None>
        <None Include="./CHANGELOG.md" Link="CHANGELOG.md">
            <PackagePath>\</PackagePath>
            <Pack>true</Pack>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <!--<ProjectReference Include="..\..\Ekom\Ekom.U10\Ekom.U10.csproj" />
      <PackageReference Update="Ekom.U10" ExcludeAssets="all" />-->
    </ItemGroup>

    <!-- Local dev: flip this to true (Directory.Build.props) -->
    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\Ekom\Ekom.U10\Ekom.U10.csproj" />
    </ItemGroup>

    <!-- CI / normal: use NuGet packages -->
    <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Ekom.U10" Version="0.2.44" />
    </ItemGroup>

</Project>
