<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <AssemblyName>Ekom.U17</AssemblyName>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <RootNamespace>Ekom.Umb</RootNamespace>

        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <!-- Package properties -->
        <PackageId>Ekom.U17</PackageId>
        <Title>Ekom Umbraco 17</Title>
        <Authors>Vettvangur</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Vettvangur/Ekom</PackageProjectUrl>
        <PackageIcon>images/VV_Logo.png</PackageIcon>
        <Description>Ekom - E-Commerce solution for Umbraco 17+</Description>
        <PackageReleaseNotes></PackageReleaseNotes>
        <Copyright>Copyright 2026</Copyright>
        <PackageTags>umbraco;ecommerce;ekom</PackageTags>

        <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>

        <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <!-- Enable NuGet package caching -->
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <!-- Package icon -->
        <None Include="../../../VV_Logo.png" Pack="true" PackagePath="images/" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
        <PackageReference Include="Umbraco.Cms.Api.Common" Version="[17.0.0,18.0.0)" />
        <PackageReference Include="Umbraco.Cms.Core" Version="[17.0.0,18.0.0)" />
        <PackageReference Include="Umbraco.Cms.Web.Common" Version="[17.0.0,18.0.0)" />
        <PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.0.0,18.0.0)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Ekom.Core\Ekom.AspNetCore\Ekom.AspNetCore.csproj" />
    </ItemGroup>

</Project>
